//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skeleton.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skeleton.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Project.
        /// </summary>
        public static string ChangeProjectButtonCaption {
            get {
                return ResourceManager.GetString("ChangeProjectButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk the skeleton.
        /// </summary>
        public static string ChooseProjectButtonCaption {
            get {
                return ResourceManager.GetString("ChooseProjectButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your poison.
        /// </summary>
        public static string ChooseProjectPageTitle {
            get {
                return ResourceManager.GetString("ChooseProjectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Choose one).
        /// </summary>
        public static string ChoosePrompt {
            get {
                return ResourceManager.GetString("ChoosePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try that again..
        /// </summary>
        public static string ConnectionErrorMessage {
            get {
                return ResourceManager.GetString("ConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovingly heaped together by &lt;a href=&quot;//twitter.com/jonfazzaro/&quot; target=&quot;_blank&quot;&gt;@@jonfazzaro&lt;/a&gt;..
        /// </summary>
        public static string FooterCopy {
            get {
                return ResourceManager.GetString("FooterCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what I did there? Heaped? &amp;#13;&amp;#13;Managed code? &amp;#13;&amp;#13;&amp;#13;&amp;#13;I&apos;ll see myself out..
        /// </summary>
        public static string FooterTooltip {
            get {
                return ResourceManager.GetString("FooterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story mapping for TFS..
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///                Did you know? &lt;a href=&quot;http://jpattonassociates.com/the-new-backlog/&quot; target=&quot;_blank&quot;&gt;The new user story backlog is a map&lt;/a&gt;.
        ///            &lt;/p&gt;
        ///            &lt;p&gt;
        ///                And until our pals on the TFS team &lt;a href=&quot;https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4130976-create-a-new-view-in-tfs-task-board-to-view-backlo&quot; target=&quot;_blank&quot;&gt;get around to building one in&lt;/a&gt;, &lt;strong&gt;Skeleton&lt;/strong&gt;&apos;s got your back.
        ///            &lt;/p&gt;
        ///            &lt;p&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LeadCopy {
            get {
                return ResourceManager.GetString("LeadCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Sorry/not sorry&amp;mdash;only for visualstudio.com or TFS 2015 right now&lt;/strong&gt;. Stay tuned for old-school support. Or &lt;a href=&quot;//github.com/jonfazzaro/skeleton&quot; target=&quot;_blank&quot;&gt;pull request me, bro&lt;/a&gt;..
        /// </summary>
        public static string ProjectCollectionUrlNote {
            get {
                return ResourceManager.GetString("ProjectCollectionUrlNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know, like https://mah.visualstudio.com/DefaultCollection.
        /// </summary>
        public static string ProjectCollectionUrlPrompt {
            get {
                return ResourceManager.GetString("ProjectCollectionUrlPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string RevertButtonCaption {
            get {
                return ResourceManager.GetString("RevertButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonCaption {
            get {
                return ResourceManager.GetString("SaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Me.
        /// </summary>
        public static string SignInButtonCaption {
            get {
                return ResourceManager.GetString("SignInButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOutButtonCaption {
            get {
                return ResourceManager.GetString("SignOutButtonCaption", resourceCulture);
            }
        }
    }
}
